# Copyright (c) 2023 Oracle and/or its affiliates. All rights reserved.
# Licensed under the GNU General Public License Version 3 as shown at https://www.gnu.org/licenses/gpl-3.0.txt.
environments:
  - environment-name: myenvironment
    globals:
      version: "1.7"
      api-server: 10.0.0.165:8091
      virtual-ip: 10.0.0.12
      remote-command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    modules:
      - module: kubernetes
        name: mycluster
        args:
          restrict-service-externalip: false
          container-registry: container-registry.oracle.com/olcne
          control-plane-nodes:
            - 10.0.0.165:8090
          worker-nodes:
            - 10.0.0.35:8090
