# Copyright 2020, Oracle Corporation and/or affiliates.  
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl

#cloud-config
package_upgrade: ${master_upgrade}
packages:
  - python3
  - chrony
timezone: ${timezone}
write_files:
  # setup script
  - path: "/root/master/master.sh"
    permissions: "0700"
    encoding: "gzip+base64"
    content: |
      ${master_sh_content}
runcmd:
  - bash /root/master/master.sh
  - echo "export OCI_CLI_AUTH=instance_principal" >>  /home/opc/.bashrc
  - touch /home/opc/master.finish
